name: Crypto Monitor CI/CD Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Build Docker image
        run: docker build -t crypto-monitor:test .

      
      - name: Run Monitor and Show Results
        run: |
          echo "Starting container in background..."
          docker run -d --name monitor-run -e EXCHANGES="binance.com,google.com,okx.com" -e CHECK_INTERVAL=2 crypto-monitor:test
          
          echo "Waiting 15 seconds for logs to accumulate..."
          sleep 15
          
          echo "--- LOGS FROM CONTAINER ---"
          docker logs monitor-run
          echo "--- END OF LOGS ---"

      
      - name: Cleanup
        run: docker rm -f monitor-run
